module.exports = {
    apps: [
        {
            name: 'nestpilot-api',
            script: './src/server.js',
            env: {
                NODE_ENV: 'development',
                PORT: 5005,
                DB_HOST: 'localhost',
                DB_USER: 'postgres',
                DB_PASS: 'P8L5fE123456_',
                DB_NAME: 'NestPilot',
                DB_DIALECT: 'postgres',
                JWT_SECRET: 'thisismynestpilotsecretkeywhichisverysecureandlongenough',
                JWT_EXPIRES_IN: '30d',
                BCRYPT_SALT_ROUNDS: 10,
            },
            env_production: {
                NODE_ENV: 'production',
                PORT: 5005,
                DB_HOST: process.env.DB_HOST || 'localhost',
                DB_USER: process.env.DB_USER || 'postgres',
                DB_PASS: process.env.DB_PASS,
                DB_NAME: process.env.DB_NAME || 'NestPilot',
                DB_DIALECT: 'postgres',
                JWT_SECRET: process.env.JWT_SECRET,
                JWT_EXPIRES_IN: '30d',
                BCRYPT_SALT_ROUNDS: 10,
            },
            instances: 1,
            exec_mode: 'fork',
            max_memory_restart: '500M',
            error_file: '.pm2/logs/nestpilot-api-error.log',
            out_file: '.pm2/logs/nestpilot-api-out.log',
            log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
            autorestart: true,
            max_restarts: 10,
            min_uptime: '10s',
            watch: false,
            ignore_watch: ['node_modules', 'uploads'],
            node_args: '--no-warnings', // Suppress all deprecation warnings including url.parse()
        },
    ],
};
